### ISSUE TITLE
Exit Intent Doesn't Trigger in Safari, Firefox

### ISSUE THREAD

**Issue by deuks** [formello-forms/popper#1]
When attempting to use the exit intent trigger, it works fine on Chrome and Edge (which is also now chromium based). However, the exit intent trigger does not fire on Safari and Firefox. 

I was able to fix this issue by changing the mouseleave property in the javascript to mouseout. Now the exit intent works on all browsers

**Comment by Tropicalista** [comment]
Seems a bug on safari: https://bugs.webkit.org/show_bug.cgi?id=4117

I will try your fix asap.
