### ISSUE TITLE
Does Not Render Custom Blocks

### ISSUE THREAD

**Issue by deuks** [formello-forms/popper#2]
This plugin supports built in blocks decently well, but if trying to insert a custom block (Something like a youtube video or even shortcode) it does not render the block properly.

I was able to fix this by applying a 'the_content' filter to the do_blocks action.

So the original do_blocks action:

https://github.com/formello-forms/popper/blob/161546cec88ef23435909bdee14ca9c0191645d2/popper.php#L160

Would be changed to something like `$popups .= apply_filter('the_content', do_blocks($popper->post_content));`

**Comment by Tropicalista** [comment]
Thanks for this.

Can you please let me know what blocks are causing this issue? Are you referring to core blocks or third party blocks?

**Comment by deuks** [comment]
I think most of the core blocks work. Things like paragraph and image are fine. I think it's probably third party blocks, like youtube or twitter or other embeds like that. Even gravity forms (Although this is really designed for formello).

So not necessarily within scope of your project, but adding the code I suggested would definitely make it more universal, and does not appear to have a negative impact on any existing functionality.

**Comment by Tropicalista** [comment]
I was thinking of adding this on [this line](https://github.com/formello-forms/popper/blob/master/popper.php#L165) instead, but if I remember this was my first try and gives some other issues.

Any thoughts?
