### ISSUE TITLE
Taxonomy Based Conditions do not work after update

### ISSUE THREAD

**Issue by deuks** [formello-forms/popper#3]
Updated to version 0.2.5 and can no longer add conditions based on taxonomy.  I can set conditions based on post title, but not based on custom post types' titles, taxonomy, tags, or custom taxonomy.  No results come up in the autocomplete, and if I try to just enter the value manually and separate using commas or the enter key, the value is wiped from the input.

Tried tons of different options: updated wordpress, updated all other plugins, deactivate all other plugins. The only thing that gets it to work again is to install the older version of your plugin.

If you have any idea of what could have caused this, and could let me know, I could assist in a fix.  Otherwise I'll have to check the changelog and start going through all the changes since the last version I know works (0.1.8)

**Comment by deuks** [comment]
I emailed you a copy of it, as I did not feel comfortable posting that much site info on a public forum. Let me know if you didn't receive it.

**Comment by deuks** [comment]
Blog Categories, Blog Tags, Custom Post Type Titles, etc. Pretty much the only thing working is the autofill for the normal post title. There are no console errors.

**Comment by Tropicalista** [comment]
Any chance you can create a temporary access to your site to let me see what's going on? You can use my email to create the account.

**Comment by deuks** [comment]
I'll ask my supervisor tomorrow and let you know, he's out for he rest of today. Thanks for your help thus far
