### ISSUE TITLE
Block validation error if width or border-radius is reset

### ISSUE THREAD

**Issue by sr-pb** [formello-forms/popper#4]
I wanted to reset the width of the modal and handle appearance by adding css on my end. If you hit the reset button in the tab "Modal Appearance" (either width and border-radius) the block will throw an error in console:

Block validation: Expected attribute `style` of value `width:500px;border-radius:0;--popper-animation:slide-in-bottom`, saw `border-radius:0;--popper-animation:slide-in-bottom`.

Only fixed numbers will work; blank values are not accepted.

But otherwise great and lightweight plugin! 💫

**Comment by Tropicalista** [comment]
This error will be solved by next release.

Unfortunately I had to make a lot of change to code, so you can experience validation error.

But from here in advance will be a lot of improvements.

Next release probably tomorrow.

I'd like to here from you if any issues.

Thanks

**Comment by sr-pb** [comment]
oops… sorry, was too fast with closing.
