### ISSUE TITLE
Unable to set a date for existing popups after upgrading to 0.4.0

### ISSUE THREAD

**Issue by sr-pb** [formello-forms/popper#5]
Cool new features in 0.4.0! Nicely done!

But after upgrading there are several warnings in columns Devices/Dates in the overview screen.

`Warning: Undefined array key "date" /popper/popper.php on line 278`
`Warning: Trying to access array offset on value of type null /popper/popper.php on line 278`
`Warning: Trying to access array offset on value of type null /popper/popper.php on line 279 `
`Warning: Trying to access array offset on value of type null /popper/popper.php on line 286 `

I managed to get around the warnings for devices, by re-checking the boxes in the Devices tab and saving the entry.

But I can't set a date in the conditions. As soon as I click on the tab Date then Gutenberg throws an error. I figure the defaults for the missing new props won't be applied for existing popups when saving.

**Comment by Tropicalista** [comment]
Hi, can you try to update to latest and let me know if it's solved?

Thanks

**Comment by sr-pb** [comment]
Your fix works perfectly, thanks!
